Add failure check

diff --git a/.github/workflows/workflow1.yaml b/.github/workflows/workflow1.yaml
--- a/.github/workflows/workflow1.yaml
+++ b/.github/workflows/workflow1.yaml
@@ -11,3 +11,4 @@ jobs:
           echo "::notice file=workflow1.yaml::starting "
           sleep 60
           echo "::notice file=workflow1.yaml::This is step from Workflow1"
+          exit 1 # fail!
